import "../styles/globals.css";
import Nav from "../components/Nav";
import Script from "next/script";
import Head from "next/head";
import "../css/styles.css";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossOrigin="anonymous"
        />
      </Head>
      <link href="css/styles.css" rel="stylesheet" />
      <Script
        src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
        crossOrigin="anonymous"
      ></Script>
      <Nav>
        <Component {...pageProps} />
      </Nav>
    </>
  );
}

export default MyApp;
